[workspace]
members = [".", "xml-parser"]
default-members = [".", "xml-parser"]

[package]
name = "rendering-project"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
ash = { version = "0.38.0", features = ["linked"]}
glfw = "0.62.0"
criterion = "0.8.2"

[dependencies]
ash = { workspace = true }
glfw = { workspace = true }
criterion = { workspace = true, optional = true }

[lib]
bench = false

[[bin]]
name = "rendering-project"
path = "src/main.rs"
bench = false

[features]
bench = ["dep:criterion"]

[profile.bench]
debug = true

[[bench]]
name = "test"
harness = false
required-features = ["bench"]